version: '2'

services:
  mongo-api:
    image: mapi:latest
    ports:
      - 8230:8230
    restart: always
    environment:
      - MONGODB_URL="mongodb://10.44.0.14:27017,10.47.0.8:27017,10.36.0.14:27017/test"
      - PORT=8230
