apiVersion: v1 
kind: Service
metadata:
  name: mapi-svc
spec:
  type: NodePort
  ports:
  - name: http
    port: 8139
    targetPort: 8139
    nodePort: 30139
    protocol: TCP
  selector:
    app: mapi
